# Conclusion

### Key Takeaways

The analysis and visualization of 311 NYC tickets helped in revealing the major problems faced by the residents of New York. Data explorations through various visualization plots helped us gain an insight not only about the different 311 issues across the different but also how efficiently these are dealt by the various agencies and the average time for resolution.

Here are the key takeaways -

-   Brooklyn had the highest 311 tickets raised as compared to the other boroughs while Staten Island had the least in the time period between Sept 2023-Nov 2023.
-   Illegal Parking complaints along with noise/cleanliness/water issues are the most frequent issues. Hence people looking for apartments to rent must keep these in mind.
-   NYPD is the most efficient in resolution of tickets among the various agencies. Even though it receives the highest 311 tickets, it is able to resolve most of them. Hence safety related conce
-   North Staten Island, west Brooklyn, southwest Queens, southern Manhattan and Bronx are some areas that resolve 311 issues the slowest on average which is a cause of concern for people planning to rent apartments in these areas.

From the analysis and plots, a person who wishes to rent an apartment in New York can take an informed decision when choosing apartments across the Boroughs of New York.

### Limitations

Due to the sheer size of the dataset (34.1M rows for 2010-2023) since it is updated daily and our resource constraints, for our analysis we focused only on a subset of the data (837k rows for Sept 2023-Nov2023). Analyzing a bigger time frame may have yielded better insights and many more interesting patterns.

### Future Directions and Lessons Learned

Through this project, we gained a better understanding of d3 and the plethora of visualization plots available for exploration of data. While our analysis and exploration mainly deals with answering questions pertaining to issues for understand the quality of life across boroughs , we can also extend our analysis to provide specific answers for questions with specific issues. Example - Which street/district in New York has the most lack of heat or hot water complaints. The answers to such questions would particularly be useful for city officials and policy makers who would be able to address these issues much more effectively. 
